version: 2

models:
  - name: daily_issue_form_normalized
    description: "Normalized data of Daily Issue Form" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: enrollment_normalized
    description: "Normalized data of Raw Enrollment Form" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: nonregular_use_tracking_normalized
    description: "Normalized data of Nonregular Use Tracking Form" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: staff_barcode_normalized
    description: "Normalized data of Staff Barcode Form" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null


  - name: use_tracking_normalized
    description: "Normalized data of Weekly Photo Form" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  - name: weekly_photo_normalized
    description: "Normalized data of Weekly Photo Form" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
