-- (
--     SELECT 'from_table1_not_in_table2' AS source, t1.*
--     FROM raw_test_data.dailyissueclean AS t1
--     EXCEPT
--     SELECT 'from_table1_not_in_table2' AS source, t2.*
--     FROM prod_final.daily_issue_clean AS t2
-- )
-- UNION ALL
-- (
--     SELECT 'from_table2_not_in_table1' AS source, t2.*
--     FROM prod_final.daily_issue_clean AS t2
--     EXCEPT
--     SELECT 'from_table2_not_in_table1' AS source, t1.*
--     FROM raw_test_data.dailyissueclean AS t1
-- );
