-- {{ref('daily_issue_form')}} -> this is referring to daily_issue_form table which is a normalized table 

-- The WITH clause defines a common table expression (CTE) called my_cte that selects columns from 
-- the daily_issue_form and facility_table tables and unnests some arrays to create new rows for 
-- each element in the arrays. The WHERE clause filters out rows where the minorissue_type column 
-- contains certain values.


with my_cte AS (SELECT _id, 
                       _submitted_by, 
                       minorissue_type, 
                       facilityname as facility, 
                       shift_type, 
                       timestamp_formatted as dateauto,
                       (to_char(timestamp_formatted::time, 'HH:MI:SS'))::time AS timeauto, 
                       _submission_time,

       unnest(array['bulb', 
                    'wiring',
                    'boring',
                    'switch',
                    'stabilizer',
                    'basin tap', 
                    'toilet tap',
                    'pipe',
                    'socket',
                    'tools',
                    'tablet',
                    'internet', 
                    'harpic etc',
                    'soap',
                    'jug',
                    'dustbin',
                    'gloves',
                    'gate',
                    'floor',
                    'wall',
                    'painting',
                    'roof',
                    'pan',
                    'pan',
                    'odor',
                    'wall',
                    'basin',
                    'drain blocked'
       
       ]) AS issue,

       unnest(array['Electrical', 
                    'Electrical',
                    'Electrical',
                    'Electrical',
                    'Electrical',
                    'Plumbing', 
                    'Plumbing',
                    'Plumbing',
                    'Plumbing',
                    'Plumbing',
                    'Technology',
                    'Technology', 
                    'Supplies',
                    'Supplies',
                    'Supplies',
                    'Supplies',
                    'Supplies',
                    'Infrastructure',
                    'Infrastructure',
                    'Infrastructure',
                    'Infrastructure',
                    'Infrastructure',
                    'Infrastructure',
                    'Cleanliness',
                    'Cleanliness',
                    'Cleanliness',
                    'Cleanliness',
                    'Cleanliness'
                    
       
       ]) AS category,

       unnest(array[electrical_group_outage_bulb, 
                    electrical_group_outage_wiring, 
                    electrical_group_outage_boring,
                    electrical_group_outage_switch,
                    electrical_group_outage_stabilizer,
                    plumbing_group_outage_basintap,
                    plumbing_group_outage_toilettap, 
                    plumbing_group_outage_pipe,
                    plumbing_group_outage_socket,
                    plumbing_group_outage_tools,
                    technology_group_outage_tablet, 
                    technology_group_outage_internet,
                    supplies_group_outage_harpicetc,
                    supplies_group_outage_soap, 
                    supplies_group_outage_jug,
                    supplies_group_outage_dustbin,
                    supplies_group_outage_glove,
                    infrastructure_group_outage_gate,
                    infrastructure_group_outage_floor,
                    infrastructure_group_outage_wall,
                    infrastructure_group_outage_painting,
                    infrastructure_group_outage_roof,
                    infrastructure_group_outage_pan,
                    cleanliness_group_outage_pan,
                    cleanliness_group_outage_odor,
                    cleanliness_group_outage_wallclean,
                    cleanliness_group_outage_basinclean,
                    cleanliness_group_outage_drainblock

                    ]) AS outage, 

       unnest(array[electrical_group_bulb_fixed, 
                    electrical_group_wiring_fixed,
                    electrical_group_boring_fixed,
                    electrical_group_switch_fixed,
                    electrical_group_stabilizer_fixed,
                    plumbing_group_basintap_fixed, 
                    plumbing_group_toilettap_fixed,
                    plumbing_group_pipe_fixed,
                    plumbing_group_socket_fixed,
                    plumbing_group_tools_fixed,
                    technology_group_tablet_fixed, 
                    technology_group_internet_fixed,  
                    supplies_group_harpicetc_fixed, 
                    supplies_group_soap_fixed,
                    supplies_group_jug_fixed,
                    supplies_group_dustbin_fixed,
                    supplies_group_glove_fixed,
                    infrastructure_group_gate_fixed,
                    infrastructure_group_floor_fixed,
                    infrastructure_group_wall_fixed,
                    infrastructure_group_painting_fixed,
                    infrastructure_group_roof_fixed,
                    infrastructure_group_pan_fixed,
                    cleanliness_group_pan_fixed,
                    cleanliness_group_odor_fixed,
                    cleanliness_group_wallclean_fixed,
                    cleanliness_group_basinclean_fixed,
                    cleanliness_group_drainblock_fixed
                    ]) AS fixed, 

       unnest(array[electrical_group_outage_bulb_full, 
                    electrical_group_outage_wiring_full,
                    electrical_group_outage_boring_full,
                    electrical_group_outage_switch_full,
                    electrical_group_outage_stabilizer_full,
                    plumbing_group_outage_basintap_full, 
                    plumbing_group_outage_toilettap_full,
                    plumbing_group_outage_pipe_full,
                    plumbing_group_outage_socket_full,
                    plumbing_group_outage_tools_full,
                    technology_group_outage_tablet_full, 
                    technology_group_outage_internet_full,
                    supplies_group_outage_harpicetc_full,
                    supplies_group_outage_soap_full,
                    supplies_group_outage_jug_full,
                    supplies_group_outage_dustbin_full,
                    supplies_group_outage_glove_full,
                    infrastructure_group_outage_gate_full,
                    infrastructure_group_outage_floor_full,
                    infrastructure_group_outage_wall_full,
                    infrastructure_group_outage_painting_full,
                    infrastructure_group_outage_roof_full,
                    infrastructure_group_outage_pan_full,
                    cleanliness_group_outage_pan_full,
                    cleanliness_group_outage_odor_full,
                    cleanliness_group_outage_wallclean_full,
                    cleanliness_group_outage_basinclean_full,
                    cleanliness_group_outage_drainblock_full
                    ]) AS full_part,

       unnest(array[electrical_group_outage_bulb_hours, 
                    electrical_group_outage_wiring_hours,
                    electrical_group_outage_boring_hours,
                    electrical_group_outage_switch_hours,
                    electrical_group_outage_stabilizer_hours,
                    plumbing_group_outage_basintap_hours, 
                    plumbing_group_outage_toilettap_hours, 
                    plumbing_group_outage_pipe_hours,
                    plumbing_group_outage_socket_hours,
                    plumbing_group_outage_tools_hours,
                    technology_group_outage_internet_hours, 
                    technology_group_outage_tablet_hours,
                    supplies_group_outage_harpicetc_hours,
                    supplies_group_outage_soap_hours,
                    supplies_group_outage_jug_hours,
                    supplies_group_outage_dustbin_hours,
                    supplies_group_outage_glove_hours,
                    infrastructure_group_outage_gate_hours,
                    infrastructure_group_outage_floor_hours,
                    infrastructure_group_outage_wall_hours,
                    infrastructure_group_outage_painting_hours,
                    infrastructure_group_outage_roof_hours,
                    infrastructure_group_outage_pan_hours,
                    cleanliness_group_outage_pan_hours,
                    cleanliness_group_outage_odor_hours,
                    cleanliness_group_outage_wallclean_hours,
                    cleanliness_group_outage_basinclean_hours,
                    cleanliness_group_outage_drainblock_hours
                    ]) AS num_hours
      
       FROM {{ref('daily_issue_form')}}

)



SELECT 
       _id,
       facility,
       _submitted_by,
       _submission_time,
       to_date(dateauto, 'YYYY-MM-DD') AS date_auto,
       timeauto AS time_auto,
       minorissue_type,
       category,
       shift_type,
       issue,
       fixed,
       true as any_issue,
       CASE full_part 
          WHEN '1' THEN 'part day'
          WHEN '2' THEN 'full day'
        END as full_partial,
       num_hours,
       CASE
          WHEN outage IS NULL THEN 'no'
          WHEN outage = '0' THEN 'no'
          WHEN outage = '1' THEN 'yes'
       ELSE outage
       END as shutdown
FROM my_cte 
where fixed is not null
order by date_auto